name: azure-python-devcon-build
run-name: Build azure-python dev-container
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
  IMAGE_NAME: azure-python-dev
  SOURCE_DIR: azure-python

jobs:
  build:
    name: Build dev container image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: devcontainers/ci@v0.3
        env:
          IMAGE_FULLNAME: 'ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}'
        with:
          subFolder: src/${{ env.SOURCE_DIR }}
          imageName: ${{ env.IMAGE_FULLNAME }}
          imageTag: ${{ env.IMAGE_TAG }}
          cacheFrom: ${{ env.IMAGE_FULLNAME }}
          push: always
