name: azure-python-devcon-build
run-name: Build azure-python dev-container
on:
  - push

jobs:
  build:
    name: Build dev container image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/azure-python
          imageName: ghcr.io/andy-krivtsov/azure-python-dev
          imageTag: latest
          cacheFrom: ghcr.io/andy-krivtsov/azure-python-dev
          push: always
